version: '3'

services:
  master:
    image: mysql:latest
    container_name: mysql-master
    environment:
      MYSQL_SERVER_ID: 1
      MYSQL_ROOT_PASSWORD: Dai2001vd
    ports:
      - "3307:3306"
    networks:
      - mysql-network

  slave:
    image: mysql:latest
    container_name: mysql-slave
    environment:
      MYSQL_SERVER_ID: 2
      MYSQL_ROOT_PASSWORD: Dai2001vd
      MYSQL_USER: repl
      MYSQL_PASSWORD: Dai2001vd
      MYSQL_MASTER_HOST: 172.20.10.5
      MYSQL_MASTER_PORT: 3307
      MYSQL_MASTER_ROOT_PASSWORD: Dai2001vd
    depends_on:
      - master
    ports:
      - "3308:3306"
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge
